{{- $fzf := (gitHubLatestRelease "junegunn/fzf").TagName -}}
{{- $starship := (gitHubLatestRelease "starship/starship").TagName -}}
{{- $rg := (gitHubLatestRelease "BurntSushi/ripgrep").TagName -}}

[".config/bat/themes/Catppuccin-mocha.tmTheme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
  refreshPeriod = "168h"

[".config/btop/themes/catppuccin_mocha.theme"]
  type = "file"
  url = "https://raw.githubusercontent.com/catppuccin/btop/main/themes/catppuccin_mocha.theme"
  refreshPeriod = "168h"

[".local/share/bash-completion/completions/fzf"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/{{ $fzf }}/shell/completion.bash"
  refreshPeriod = "168h"

[".bashrc.d/50-fzf-key-bindings.sh"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/fzf/{{ $fzf }}/shell/key-bindings.bash"
  refreshPeriod = "168h"

[".local/bin/fzf"]
  type = "file"
  url = "https://github.com/junegunn/fzf/releases/download/{{ $fzf }}/fzf-{{ trimPrefix "v" $fzf }}-linux_amd64.tar.gz"
  executable = true
  refreshPeriod = "168h"
  [".local/bin/fzf".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "fzf"]

[".local/bin/starship"]
  type = "file"
  url = "https://github.com/starship/starship/releases/download/{{ $starship }}/starship-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  refreshPeriod = "168h"
  [".local/bin/starship".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "starship"]

[".local/bin/rg"]
  type = "file"
  url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $rg }}/ripgrep-{{ $rg }}-x86_64-unknown-linux-musl.tar.gz"
  executable = true
  refreshPeriod = "168h"
  [".local/bin/rg".filter]
    command = "tar"
    args = ["--extract", "--file", "/dev/stdin", "--gzip", "--strip-components=1", "--wildcards", "--to-stdout", "*/rg"]
